name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01eee49edce2b6d6674e683e47f00183ce94be8f280e8ef59dadef42e96a76c2"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
