name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ce66321b4643d296d34f69ea618838df7ac9fd3f093942f0df8a8f41f65d3e0"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
