name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d42379d295daeac365c4a717ef202915be43fe199577aa15a180a831abded7bb"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
