name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1691056753c5c807bc9ccb0fb35751224eabe38db33ee4ed6b5158c05c3661b0"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
