name = "All-of-Fabric-3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1cc10aa0b0777fc344dcc12e68547e8f0bf8c5f986f69de6e1aeab08cba7817"

[versions]
fabric = "0.11.7"
minecraft = "1.16.5"
