name = "Botania Tweakers"
filename = "BotaniaTweakers-0.9.6+1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3183/999/BotaniaTweakers-0.9.6+1.16.4.jar"
hash-format = "murmur2"
hash = "597772584"

[update]
[update.curseforge]
file-id = 3183999
project-id = 426613
