name = "Mythic Mounts"
filename = "mythic-mounts-1.16.5-3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3524/617/mythic-mounts-1.16.5-3.0.jar"
hash-format = "murmur2"
hash = "4209359821"

[update]
[update.curseforge]
file-id = 3524617
project-id = 517650
