name = "Sandwichable"
filename = "sandwichable-1.2-rc2+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3514/942/sandwichable-1.2-rc2+1.16.jar"
hash-format = "murmur2"
hash = "2752086204"

[update]
[update.curseforge]
file-id = 3514942
project-id = 374143
